export const themes = {
    matrix: {
      name: 'Matrix',
      bg: '#030712',
      text: '#4ade80',
      primary: '#4ade80',
      hoverText: 'hover:text-[#4ade80]',
      secondaryText: 'text-gray-400',
      border: 'border-gray-800',
      prompt: 'text-green-500',
      ai: 'text-cyan-400',
      error: 'text-red-400',
      success: 'text-green-400',
      accent: 'text-purple-400',
      termBg: 'bg-gray-900'
    },
    dracula: {
      name: 'Dracula',
      bg: '#282a36',
      text: '#f8f8f2',
      primary: '#bd93f9',
      hoverText: 'hover:text-[#f8f8f2]',
      secondaryText: 'text-[#6272a4]',
      border: 'border-[#44475a]',
      prompt: 'text-[#ff79c6]',
      ai: 'text-[#8be9fd]',
      error: 'text-[#ff5555]',
      success: 'text-[#50fa7b]',
      accent: 'text-[#bd93f9]',
      termBg: 'bg-[#1e1f29]',
    },
    monokai: {
      name: 'Monokai',
      bg: '#272822',
      text: '#f8f8f2',
      primary: '#ae81ff',
      hoverText: 'hover:text-[#f8f8f2]',
      secondaryText: 'text-[#75715e]',
      border: 'border-[#3e3d32]',
      prompt: 'text-[#f92672]',
      ai: 'text-[#66d9ef]',
      error: 'text-[#f92672]',
      success: 'text-[#a6e22e]',
      accent: 'text-[#ae81ff]',
      termBg: 'bg-[#1e1e1e]',
    },
    cyberpunk: {
      name: 'Cyberpunk',
      bg: '#0a0e27',
      text: '#00ff9f',
      primary: '#ff2a6d',
      hoverText: 'hover:text-[#00ff9f]',
      secondaryText: 'text-[#5b6ad0]',
      border: 'border-[#ff2a6d]',
      prompt: 'text-[#ff2a6d]',
      ai: 'text-[#00d9ff]',
      error: 'text-[#ff2a6d]',
      success: 'text-[#00ff9f]',
      accent: 'text-[#d1f7ff]',
      termBg: 'bg-[#05081d]',
    },
    hacker: {
      name: 'Hacker',
      bg: '#000000',
      text: '#00ff00',
      primary: '#00ff00',
      hoverText: 'hover:text-[#00ff00]',
      secondaryText: 'text-[#008800]',
      border: 'border-[#00ff00]',
      prompt: 'text-[#00ff00]',
      ai: 'text-[#00ffff]',
      error: 'text-[#ff0000]',
      success: 'text-[#00ff00]',
      accent: 'text-[#ffff00]',
      termBg: 'bg-[#0a0a0a]',
    }
  };

  export type ThemeKey = keyof typeof themes;
  